services:
  configurator:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        APP: configurator
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5174:5174"

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        APP: web
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    env_file:
      - ./apps/web/.env
