export const questionsData = [
  {
    id: 1,
    question: "What is your age?",
    category: "Demographics",
    type: "number",
    required: true,
    selected: true,
  },
  {
    id: 2,
    question: "What is your biological sex?",
    category: "Demographics",
    type: "single choice",
    required: true,
    selected: true,
  },
  {
    id: 3,
    question: "What is your height in centimeters?",
    category: "Demographics",
    type: "number",
    required: true,
    selected: false,
  },
  {
    id: 4,
    question: "What is your current weight in kilograms?",
    category: "Demographics",
    type: "number",
    required: true,
    selected: false,
  },
  {
    id: 5,
    question: "Do you have any of the following medical conditions?",
    category: "Medical History",
    type: "multi choice",
    required: false,
    selected: false,
  },
  {
    id: 6,
    question: "Please list any medications you are currently taking",
    category: "Medical History",
    type: "text",
    required: false,
    selected: false,
  },
  {
    id: 7,
    question: "Do you have any known allergies?",
    category: "Medical History",
    type: "text",
    required: false,
    selected: false,
  },
  {
    id: 8,
    question: "What are your primary health and fitness goals?",
    category: "Lifestyle",
    type: "multi choice",
    required: true,
    selected: false,
  },
  {
    id: 9,
    question: "How often do you exercise per week?",
    category: "Fitness",
    type: "single choice",
    required: true,
    selected: false,
  },
  {
    id: 10,
    question: "What types of exercise do you regularly do?",
    category: "Fitness",
    type: "multi choice",
    required: false,
    selected: false,
  },
  {
    id: 11,
    question: "How many hours of sleep do you get per night on average?",
    category: "Lifestyle",
    type: "single choice",
    required: true,
    selected: false,
  },
  {
    id: 12,
    question: "How would you rate your sleep quality?",
    category: "Lifestyle",
    type: "single choice",
    required: false,
    selected: false,
  },
  {
    id: 13,
    question: "How would you rate your current stress level?",
    category: "Mental Health",
    type: "single choice",
    required: true,
    selected: false,
  },
  {
    id: 14,
    question: "Which best describes your current diet?",
    category: "Nutrition",
    type: "single choice",
    required: true,
    selected: false,
  },
  {
    id: 15,
    question: "How many glasses of water do you drink per day?",
    category: "Nutrition",
    type: "single choice",
    required: false,
    selected: false,
  },
  {
    id: 16,
    question: "How often do you consume alcohol?",
    category: "Lifestyle",
    type: "single choice",
    required: false,
    selected: false,
  },
  {
    id: 17,
    question: "Do you smoke tobacco products?",
    category: "Lifestyle",
    type: "single choice",
    required: true,
    selected: false,
  },
  {
    id: 18,
    question: "What supplements or vitamins do you currently take?",
    category: "Nutrition",
    type: "text",
    required: false,
    selected: false,
  },
  {
    id: 19,
    question: "Do you have a family history of heart disease?",
    category: "Medical History",
    type: "boolean",
    required: false,
    selected: false,
  },
  {
    id: 20,
    question: "Do you have a family history of diabetes?",
    category: "Medical History",
    type: "boolean",
    required: false,
    selected: false,
  },
  {
    id: 21,
    question: "Do you have regular menstrual cycles? (if applicable)",
    category: "Demographics",
    type: "boolean",
    required: false,
    selected: false,
  },
  {
    id: 22,
    question: "Are you currently pregnant or trying to conceive?",
    category: "Demographics",
    type: "boolean",
    required: false,
    selected: false,
  },
  {
    id: 23,
    question: "How would you describe your daily work activity level?",
    category: "Lifestyle",
    type: "single choice",
    required: true,
    selected: false,
  },
  {
    id: 24,
    question: "Are you currently receiving mental health support or therapy?",
    category: "Mental Health",
    type: "boolean",
    required: false,
    selected: false,
  },
  {
    id: 25,
    question:
      "Do you consent to biometric data collection via face scan technology?",
    category: "Demographics",
    type: "boolean",
    required: true,
    selected: false,
  },
];

export const categories = [
  "Demographics",
  "Medical History",
  "Lifestyle",
  "Fitness",
  "Mental Health",
  "Nutrition",
];

export const questionTypes = [
  "text",
  "number",
  "single choice",
  "multi choice",
  "boolean",
];
